// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-7gI3GupKLzdpinhUK3Ea1hz7oHMvNOQ',
    appId: '1:63577826035:web:86aa8ccbd9a38d572d0d86',
    messagingSenderId: '63577826035',
    projectId: 'study-plan-mastery',
    authDomain: 'study-plan-mastery.firebaseapp.com',
    storageBucket: 'study-plan-mastery.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuzTaJqPm317KjZeSMqgJPg9Co50NtJQ8',
    appId: '1:63577826035:android:e2c091ac9c046f1a2d0d86',
    messagingSenderId: '63577826035',
    projectId: 'study-plan-mastery',
    storageBucket: 'study-plan-mastery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_pPKnPFO_84x0MtUofuPBNei-9JdV9NU',
    appId: '1:63577826035:ios:b8678c0ea36185f82d0d86',
    messagingSenderId: '63577826035',
    projectId: 'study-plan-mastery',
    storageBucket: 'study-plan-mastery.appspot.com',
    iosClientId: '63577826035-hb2ijri8vbir1mr8ng23j1b535jcgg71.apps.googleusercontent.com',
    iosBundleId: 'com.dashboard.app.studyPlanStudentDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_pPKnPFO_84x0MtUofuPBNei-9JdV9NU',
    appId: '1:63577826035:ios:b8678c0ea36185f82d0d86',
    messagingSenderId: '63577826035',
    projectId: 'study-plan-mastery',
    storageBucket: 'study-plan-mastery.appspot.com',
    iosClientId: '63577826035-hb2ijri8vbir1mr8ng23j1b535jcgg71.apps.googleusercontent.com',
    iosBundleId: 'com.dashboard.app.studyPlanStudentDashboard',
  );
}
